apiVersion: apps/v1
kind: Deployment
metadata:
  name: literature-app-{{ .Values.podLabels.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: literature-app
      color: {{ .Values.podLabels.color }} 
  template:
    metadata:
      labels:
        app: literature-app
        color: {{ .Values.podLabels.color }} 
    spec:
      containers:
        - name: literature-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
