apiVersion: apps/v1
kind: Deployment
metadata:
  name: literature-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: literature-app
  template:
    metadata:
      labels:
        app: literature-app
    spec:
      containers:
        - name: literature-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
