apiVersion: v1
kind: Service
metadata:
  name: literature-app-service
  namespace: jenkins
  annotations:
    # TRIK SAKTI: Biar Helm nggak rebutan metadata ownership
    "helm.sh/resource-policy": keep
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: literature-app
    # Label color sengaja dikosongin biar di-patch Jenkins
